### ISSUE TITLE
없는 유저를 요청했을때 200이 뜸

### ISSUE THREAD

**Issue by cos18** [404-DriverNotFound/team-a#100]
<img width="702" alt="Screen Shot 2021-08-03 at 5 34 53 PM" src="https://user-images.githubusercontent.com/33975709/127984775-dcb870ac-af15-440e-8114-a9bfe0be2f29.png">
@aymin91 @Yechan0815 확인 부탁드립니다.

**Comment by aymin91** [comment]
이슈 확인했습니다 수정할게요
