### ISSUE TITLE
<중요> 팀명 정하기

### ISSUE THREAD

**Issue by aymin91** [404-DriverNotFound/team-a#133]
저희 팀의 팀명이 team-a 입니다..
심각합니다..
멋진 팀명을 정해주세요.

**Comment by cos18** [comment]
일단 임시 이름이였던 `Mighty Pong` 먼저 넣어봅니다 ㅎㅎ...

**Comment by aymin91** [comment]
저는 noCovid 하겠습니다

**Comment by aymin91** [comment]
마음에 드는 팀명에 👍 를 달아주세요

**Comment by kmin-283** [comment]
innerCircle[end-1] 추천합니다ㅋㅋ
