### ISSUE TITLE
프론트에서 Network Error 가 납니다

### ISSUE THREAD

**Issue by Yechan0815** [404-DriverNotFound/team-a#157]
![제목 없음](https://user-images.githubusercontent.com/12230655/128652315-6cbe1ee7-4bcc-4a2d-a650-86a76e047529.png)

**Comment by kmin-283** [comment]
![7](https://user-images.githubusercontent.com/63279334/128653425-342cbf3a-5179-467e-aa02-f7e7d1a7f8c0.jpg)
콘솔을 확인하면 위와같은 에러가 발생하는데

localhost:3000 으로 된 부분을 3.35.175:3000으로 변경해보면 어떨까요?

**Comment by Yechan0815** [comment]
확인했습니다 감사합니다!
