### ISSUE TITLE
어드민이 임명되지 않음

### ISSUE THREAD

**Issue by cos18** [404-DriverNotFound/team-a#198]
<img width="582" alt="Screen Shot 2021-08-17 at 2 01 56 AM" src="https://user-images.githubusercontent.com/33975709/129601578-f359df07-c045-4064-890c-40b0ad745c8b.png">

<img width="394" alt="Screen Shot 2021-08-17 at 2 02 13 AM" src="https://user-images.githubusercontent.com/33975709/129601605-cf1a2f6d-8da5-431d-abe1-2fdcf2293ea4.png">

채널에 존재하는 유저를 어드민으로 임명하려 했을때 `err: "This id 1 user is not in this channel. Check the user id"`와 함꺠 400 Bad Request가 뜹니다.

**Comment by aymin91** [comment]
main으로 바로 푸시했습니다. 
param으로 들어올 때 , type은 number이지만 string으로 읽히는 tranform 오류 입니다.
