### ISSUE TITLE
커뮤니티 데이터를 받아올 때 유저의 정보가 필요함

### ISSUE THREAD

**Issue by kmin-283** [404-DriverNotFound/team-a#89]
현재 커뮤니티의 친구를 생성할 때 id만 사용해서 친구를 생성하고 데이터를 받아오는데

받아오는 데이터는 유저의 id뿐만 아니라 다른 정보도 함께 있어야 함.

**Comment by cos18** [comment]
#88 리뷰로 작성해두었는데, 사실 프론트에서 개별 유저 정보를 N번 요청하게 되면 서버에 과부하가 일어나게 됩니다.
실제로는 백엔드에서 유저 정보까지 같이 보내주면 프론트가 요청 한번으로 렌더링이 가능합니다.
@aymin91 @Yechan0815 확인하시고 의견 남겨주세요~

**Comment by aymin91** [comment]
이슈 확인했습니다
코드 확인 후 다시 코멘트 남길게요
